using Blazma.Core.Analysis;
using Blazma.Core.Samples;
using Blazma.Reporting.Interop;
using YamlDotNet.Core;
using YamlDotNet.RepresentationModel;

namespace Blazma.Reporting.Tests;

public class SigmaGeneratorTests
{
    public static TheoryData<string> TrickyValues => new()
    {
        "plain value", "it's", "a: b", "key:value", "# comment", "x #y", "x#y", @"C:\Users\x\a.exe", @"\\server\share",
        "\"quoted\"", "'single'", "true", "No", "off", "null", "~", "123", "1.5", "0x1F", "2026-10-07", ".inf",
        "-dash", "- item", "[x]", "{a: 1}", "&anchor", "*alias", "!tag", "%directive", "@at", "`tick", "|pipe", ">fold",
        "?question", ",comma", "line1\nline2", "cr\rlf", "tab\there", "trailing ", " leading", "", " ",
        "برنامج: \"اختبار\" #1", "emoji 😀", "nul\0byte", "bell\u0007", "ls\u2028ep", "bom\uFEFF", "---", "...", "=x",
    };

    [Theory]
    [MemberData(nameof(TrickyValues))]
    public void Scalars_round_trip_through_a_yaml_parser(string value)
    {
        var yaml = "k: " + YamlScalar.Write(value) + "\n";
        var stream = new YamlStream();
        stream.Load(new StringReader(yaml));
        var node = (YamlScalarNode)((YamlMappingNode)stream.Documents[0].RootNode).Children[new YamlScalarNode("k")];
        Assert.Equal(value.Replace('\0', '\0'), node.Value);

        // Anything a resolver could read as a bool, null, number or date is quoted.
        if (value is "true" or "No" or "off" or "null" or "~" or "123" or "1.5" or "0x1F" or "2026-10-07" or ".inf" or "")
            Assert.NotEqual(ScalarStyle.Plain, node.Style);
    }

    [Fact]
    public void Sigma_values_escape_wildcards_and_only_the_backslashes_that_need_it()
    {
        Assert.Equal(@"a\*b\?c", SigmaGenerator.EscapeValue("a*b?c"));
        Assert.Equal(@"C:\x\\\*", SigmaGenerator.EscapeValue(@"C:\x\*"));
        Assert.Equal(@"\\\server\share", SigmaGenerator.EscapeValue(@"\\server\share"));
        Assert.Equal(@"\Software\Run", SigmaGenerator.EscapeValue(@"\Software\Run"));
        Assert.Equal(@"end\", SigmaGenerator.EscapeValue(@"end\"));
    }

    [Fact]
    public void Paths_are_generalized_beyond_the_user_profile()
    {
        Assert.Equal(@"\AppData\Roaming\x\a.exe", SigmaGenerator.GeneralizePath(@"C:\Users\bob\AppData\Roaming\x\a.exe"));
        Assert.Equal(@"\AppData\Roaming\x\a.exe", SigmaGenerator.GeneralizePath(@"C:\Users\<user>\AppData\Roaming\x\a.exe"));
        Assert.Equal(@"\ProgramData\a.exe", SigmaGenerator.GeneralizePath(@"D:\ProgramData\a.exe"));
    }

    [Fact]
    public void Demo_rules_are_valid_sigma_drafts()
    {
        var a = TestData.Demo();
        var text = new SigmaGenerator().Generate(a, TestData.Options());
        var docs = Load(text);
        Assert.True(docs.Count >= 5);

        foreach (var d in docs)
        {
            Assert.False(string.IsNullOrWhiteSpace(Str(d, "title")));
            Assert.True(Guid.TryParse(Str(d, "id"), out _));
            Assert.Equal("experimental", Str(d, "status"));
            Assert.Equal(SigmaGenerator.Author, Str(d, "author"));
            Assert.Equal("2026-10-07", Str(d, "date"));
            Assert.Contains("Draft generated by Blazma Sandbox", Str(d, "description"), StringComparison.Ordinal);
            Assert.Contains(Str(d, "level"), new[] { "informational", "low", "medium", "high", "critical" });
            var logsource = (YamlMappingNode)d["logsource"];
            Assert.Equal("windows", Str(logsource, "product"));
            Assert.Contains(Str(logsource, "category"), new[] { "process_creation", "registry_set", "file_event", "dns_query", "network_connection" });
            Assert.Equal("selection", Str((YamlMappingNode)d["detection"], "condition"));
            Assert.NotEmpty(((YamlSequenceNode)d["falsepositives"]).Children);
            if (d.Children.ContainsKey(new YamlScalarNode("tags")))
                Assert.All(((YamlSequenceNode)d["tags"]).Children, t => Assert.Matches(@"^attack\.(t\d{4}(\.\d{3})?|[a-z_]+)$", ((YamlScalarNode)t).Value));
        }
        Assert.Equal(docs.Count, docs.Select(d => Str(d, "id")).Distinct().Count());

        var ps = Rule(docs, "process_creation", d => Str(Selection(d), "Image|endswith") == @"\powershell.exe");
        var psSel = Selection(ps);
        Assert.Equal(@"\updater.exe", Str(psSel, "ParentImage|endswith"));
        Assert.Equal(@"\powershell.exe", Str(psSel, "Image|endswith"));
        Assert.Equal(["-EncodedCommand", "-NoProfile", "-WindowStyle"], ((YamlSequenceNode)psSel["CommandLine|contains|all"]).Children.Select(c => ((YamlScalarNode)c).Value));
        Assert.Contains("attack.t1059.001", ((YamlSequenceNode)ps["tags"]).Children.Select(c => ((YamlScalarNode)c).Value));
        Assert.Contains("attack.execution", ((YamlSequenceNode)ps["tags"]).Children.Select(c => ((YamlScalarNode)c).Value));

        var reg = Selection(Rule(docs, "registry_set"));
        Assert.Equal(@"\Software\Microsoft\Windows\CurrentVersion\Run\ContosoUpdater", Str(reg, "TargetObject|endswith"));
        Assert.Equal(@"\updater.exe", Str(reg, "Details|contains"));

        var file = Selection(Rule(docs, "file_event"));
        Assert.Equal(@"\AppData\Roaming\ContosoUpdate\updater.exe", Str(file, "TargetFilename|endswith"));

        var dns = Rule(docs, "dns_query");
        Assert.Contains("api.contoso-update.example", ((YamlSequenceNode)Selection(dns)["QueryName"]).Children.Select(c => ((YamlScalarNode)c).Value));

        var net = Rule(docs, "network_connection", d => Str(d, "level") == "high");
        Assert.Equal("198.51.100.7", Str(Selection(net), "DestinationIp"));
        Assert.Equal("true", Str(Selection(net), "Initiated"));
    }

    [Fact]
    public void Output_is_deterministic_and_redacted()
    {
        var gen = new SigmaGenerator(_ => new Redactor(["WDAGUtilityAccount"], ["SANDBOX-PC"]));
        var first = gen.Generate(TestData.Demo(), TestData.Options(redact: true));
        Assert.Equal(first, gen.Generate(TestData.Demo(), TestData.Options(redact: true)));
        Assert.DoesNotContain("WDAGUtilityAccount", first, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("\r", first, StringComparison.Ordinal);
    }

    [Fact]
    public void Nothing_observed_means_no_rules()
    {
        var sample = TestData.Sample("empty.exe");
        var a = new AnalysisResult { AnalysisId = Guid.Empty, Sample = sample, Options = new AnalysisOptions(), ProviderId = "demo", StartedAt = TestData.Start };
        Assert.Equal(string.Empty, new SigmaGenerator().Generate(a, TestData.Options()));
        Assert.Equal(FileKind.Executable, sample.Kind);
    }

    private static List<YamlMappingNode> Load(string text)
    {
        var stream = new YamlStream();
        stream.Load(new StringReader(text));
        return stream.Documents.Select(d => (YamlMappingNode)d.RootNode).ToList();
    }

    private static string Str(YamlMappingNode node, string key) => ((YamlScalarNode)node[key]).Value!;

    private static YamlMappingNode Selection(YamlMappingNode rule) => (YamlMappingNode)((YamlMappingNode)rule["detection"])["selection"];

    private static YamlMappingNode Rule(List<YamlMappingNode> docs, string category, Func<YamlMappingNode, bool>? where = null) =>
        docs.First(d => Str((YamlMappingNode)d["logsource"], "category") == category && (where?.Invoke(d) ?? true));
}
