using System.Text;
using System.Text.RegularExpressions;
using Blazma.Analysis.Text;
using Blazma.Core.Abstractions;
using Blazma.Core.Analysis;
using Blazma.Core.Events;
using Blazma.Core.Indicators;
using Blazma.Core.Processes;

namespace Blazma.Reporting.Interop;

/// <summary>
/// Draft Sigma rules (https://sigmahq.io/docs/basics/rules.html) from what one analysis
/// observed: processes the sample tree started, persistence registry values, dropped
/// executables, DNS queries and connections. They are starting points for a detection
/// engineer, so every rule is <c>status: experimental</c> and says it was generated; values
/// are taken from the analysis as observed, with user-profile paths generalised.
/// </summary>
public sealed partial class SigmaGenerator
{
    public const string Author = "Blazma Sandbox (generated)";

    private const int MaxSwitches = 5;

    private readonly Func<bool, Redactor>? _redactorFactory;

    public SigmaGenerator(Func<bool, Redactor>? redactorFactory = null) => _redactorFactory = redactorFactory;

    /// <summary>All rules as one YAML stream (documents separated by <c>---</c>). Empty when nothing was observed to write a rule for.</summary>
    public string Generate(AnalysisResult a, ExportOptions options)
    {
        var r = InteropData.Redactor(_redactorFactory, options.Redact);
        var rules = new List<Rule>();
        rules.AddRange(ProcessRules(a, r));
        rules.AddRange(RegistryRules(a, r));
        rules.AddRange(IndicatorRules(a, r, IndicatorType.FilePath, "file_event", "TargetFilename|endswith", GeneralizePath, "Creation of executable files", "Legitimate software installing or updating files with the same names in the same folders"));
        rules.AddRange(IndicatorRules(a, r, IndicatorType.Domain, "dns_query", "QueryName", v => v.TrimEnd('.'), "DNS queries to domains", "Legitimate use of the same domains"));
        rules.AddRange(IndicatorRules(a, r, IndicatorType.IpAddress, "network_connection", "DestinationIp", v => InteropData.IpFamily(v) is null ? null : v, "Connections to addresses", "Legitimate services hosted at the same addresses (shared hosting, CDNs)"));
        if (rules.Count == 0) return string.Empty;

        var sb = new StringBuilder();
        sb.Append("# Draft Sigma rules generated by Blazma Sandbox from one analysis. Review and test before use.\n");
        for (var i = 0; i < rules.Count; i++)
        {
            if (i > 0) sb.Append("---\n");
            Write(sb, rules[i], a);
        }
        return sb.ToString();
    }

    /// <summary>
    /// Sigma string escaping: <c>*</c> and <c>?</c> are wildcards and <c>\</c> escapes them, so
    /// literal wildcards are escaped, and a backslash is doubled only where it would
    /// otherwise escape the next character.
    /// </summary>
    public static string EscapeValue(string value)
    {
        var sb = new StringBuilder(value.Length + 4);
        for (var i = 0; i < value.Length; i++)
        {
            var c = value[i];
            if (c is '*' or '?') sb.Append('\\').Append(c);
            else if (c == '\\' && i + 1 < value.Length && value[i + 1] is '\\' or '*' or '?') sb.Append(@"\\");
            else sb.Append(c);
        }
        return sb.ToString();
    }

    public static string LevelFor(Severity severity) => severity switch
    {
        Severity.Critical => "critical",
        Severity.High => "high",
        Severity.Medium => "medium",
        Severity.Low => "low",
        _ => "informational",
    };

    public static string LevelFor(IndicatorStatus status) => status switch
    {
        IndicatorStatus.HighRisk or IndicatorStatus.WatchlistMatch or IndicatorStatus.KnownReputation => "high",
        IndicatorStatus.Suspicious => "medium",
        IndicatorStatus.Observed => "low",
        _ => "informational",
    };

    private sealed record Rule(string Key, string Title, string Description, string Category, IReadOnlyList<(string Field, IReadOnlyList<string> Values)> Selection, IReadOnlyList<AttackReference> Techniques, string FalsePositive, string Level);

    private static IEnumerable<Rule> ProcessRules(AnalysisResult a, Redactor r)
    {
        var tree = a.AllProcesses.Where(n => n.InAnalyzedTree).ToList();
        var byKey = tree.ToDictionary(n => n.Key);
        var children = tree.Where(n => !n.IsSample && n.ParentKey is { } p && byKey.ContainsKey(p))
            .GroupBy(n => (Parent: byKey[n.ParentKey!.Value].Name.ToLowerInvariant(), Child: n.Name.ToLowerInvariant()));

        foreach (var g in children.OrderBy(g => g.Key.Parent, StringComparer.Ordinal).ThenBy(g => g.Key.Child, StringComparer.Ordinal))
        {
            var parent = r.Apply(byKey[g.First().ParentKey!.Value].Name)!;
            var child = r.Apply(g.First().Name)!;
            if (InteropData.IsRedacted(parent) || InteropData.IsRedacted(child)) continue;

            // Switches every instance used: the stable part of the command line.
            var switches = g.Select(n => Switches(r.Apply(n.CommandLine)).ToHashSet(StringComparer.OrdinalIgnoreCase))
                .Aggregate((x, y) => { x.IntersectWith(y); return x; })
                .OrderByDescending(x => x.Length).ThenBy(x => x, StringComparer.OrdinalIgnoreCase).Take(MaxSwitches) // longer switches are more specific
                .Order(StringComparer.OrdinalIgnoreCase).ToList();

            var selection = new List<(string, IReadOnlyList<string>)>
            {
                ("ParentImage|endswith", ["\\" + parent]),
                ("Image|endswith", ["\\" + child]),
            };
            if (switches.Count > 0) selection.Add((switches.Count == 1 ? "CommandLine|contains" : "CommandLine|contains|all", switches));

            var seqs = g.Select(n => n.StartEventSequence).ToList();
            var level = InteropData.WorstFindingSeverity(a, seqs) is { } s ? LevelFor(s) : "low";
            yield return new Rule($"process|{parent}|{child}|{string.Join(' ', switches)}",
                $"{child} started by {parent}",
                $"{child} was started by {parent} during the analysis{(switches.Count > 0 ? " with " + string.Join(" ", switches) : "")}.",
                "process_creation", selection, InteropData.TechniquesFor(a, seqs),
                $"Legitimate software where {parent} starts {child} with the same arguments", level);
        }
    }

    /// <summary>Command-line switches (-x, /x), skipping the program itself and anything carrying a user path or redaction.</summary>
    private static IEnumerable<string> Switches(string? commandLine)
    {
        if (string.IsNullOrWhiteSpace(commandLine)) yield break;
        var first = true;
        foreach (Match m in ArgumentRegex().Matches(commandLine))
        {
            if (first) { first = false; continue; }
            var token = m.Value;
            if (token.Length is >= 2 and <= 32 && token[0] is '-' or '/' && char.IsAsciiLetter(token[1])
                && !InteropData.IsRedacted(token) && !token.Contains('\\', StringComparison.Ordinal) && !token.Contains('"', StringComparison.Ordinal))
                yield return token;
        }
    }

    private static IEnumerable<Rule> RegistryRules(AnalysisResult a, Redactor r)
    {
        var detections = a.Persistence
            .Where(p => (p.ByAnalyzedTree || p.PointsToDroppedFile) && p.Target.StartsWith("HK", StringComparison.OrdinalIgnoreCase))
            .GroupBy(p => p.Target, StringComparer.OrdinalIgnoreCase)
            .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase);

        foreach (var g in detections)
        {
            var target = r.Apply(PathRules.NormalizeRegistryKey(g.Key))!;
            var cut = target.IndexOf('\\', StringComparison.Ordinal);
            if (cut < 0 || InteropData.IsRedacted(target)) continue;
            var keyPath = target[cut..]; // without the hive: Sysmon reports HKCU as HKU\<SID>

            var selection = new List<(string, IReadOnlyList<string>)> { ("TargetObject|endswith", [keyPath]) };
            var program = g.Select(p => ProgramName(r.Apply(p.Value))).FirstOrDefault(x => x is not null);
            if (program is not null) selection.Add(("Details|contains", ["\\" + program]));

            var seqs = g.SelectMany(p => p.EventSequences).ToList();
            var techniques = InteropData.TechniquesFor(a, seqs);
            if (techniques.Count == 0 && TechniqueFor(g.First().Technique) is { } fallback) techniques = AttackReference.ResolveAll([fallback]);
            var severity = g.Max(p => p.Severity);
            yield return new Rule($"registry|{keyPath}|{program}",
                $"Persistence registry value {keyPath[(keyPath.LastIndexOf('\\') + 1)..]} set",
                $"A process in the analyzed tree set {target}{(program is null ? "" : " to start " + program)}.",
                "registry_set", selection, techniques,
                "Legitimate software registering the same startup entry", LevelFor(severity));
        }
    }

    /// <summary>The ATT&amp;CK technique a persistence location is documented under, when no finding named one.</summary>
    private static string? TechniqueFor(PersistenceTechnique technique) => technique switch
    {
        PersistenceTechnique.RunKey or PersistenceTechnique.StartupFolder => "T1547.001",
        PersistenceTechnique.WinlogonHelper => "T1547.004",
        PersistenceTechnique.ImageFileExecutionOptions => "T1546.012",
        PersistenceTechnique.AppInitDlls => "T1546.010",
        PersistenceTechnique.ActiveSetup => "T1547.014",
        PersistenceTechnique.ScheduledTask => "T1053.005",
        PersistenceTechnique.Service => "T1543.003",
        _ => null,
    };

    private static string? ProgramName(string? data)
    {
        if (string.IsNullOrEmpty(data)) return null;
        var m = ProgramRegex().Match(data);
        return m.Success ? m.Groups["name"].Value : null;
    }

    /// <summary>One rule per detection level, listing the indicator values of that level.</summary>
    private static IEnumerable<Rule> IndicatorRules(AnalysisResult a, Redactor r, IndicatorType type, string category, string field, Func<string, string?> shape, string what, string falsePositive)
    {
        var groups = a.Indicators.Where(i => i.Type == type && i.Status != IndicatorStatus.Informational)
            .Select(i => (Indicator: i, Value: shape(r.Apply(i.Value)!)))
            .Where(x => !string.IsNullOrEmpty(x.Value))
            .GroupBy(x => LevelFor(x.Indicator.Status))
            .OrderBy(g => LevelRank(g.Key));

        foreach (var g in groups)
        {
            var values = g.Select(x => x.Value!).Distinct(StringComparer.OrdinalIgnoreCase).Order(StringComparer.Ordinal).ToList();
            var selection = new List<(string, IReadOnlyList<string>)> { (field, values) };
            if (category == "network_connection") selection.Add(("Initiated", ["true"]));
            var techniques = InteropData.TechniquesFor(a, g.SelectMany(x => x.Indicator.EventSequences));
            var statuses = string.Join(", ", g.Select(x => x.Indicator.Status).Distinct().Order());
            var title = $"{what} seen in a Blazma analysis of {r.Apply(a.Sample.FileName)} ({g.Key})";
            yield return new Rule($"{category}|{g.Key}|{string.Join('|', values)}", title,
                $"{what} seen during the analysis ({values.Count}). Blazma indicator status: {statuses}.",
                category, selection, techniques, falsePositive, g.Key);
        }
    }

    private static int LevelRank(string level) => level switch
    {
        "critical" => 0,
        "high" => 1,
        "medium" => 2,
        "low" => 3,
        _ => 4,
    };

    /// <summary>
    /// Makes a path match on other machines: the user profile becomes a suffix match from the
    /// folder below it, and the drive letter is dropped.
    /// </summary>
    public static string? GeneralizePath(string path)
    {
        var p = PathRules.NormalizeFilePath(path);
        if (UserProfileRegex().Match(p) is { Success: true } m) return "\\" + m.Groups["rest"].Value;
        if (DriveRegex().Match(p) is { Success: true } d) return d.Groups["rest"].Value;
        return InteropData.IsRedacted(p) ? null : p;
    }

    private static void Write(StringBuilder sb, Rule rule, AnalysisResult a)
    {
        static string Q(string v) => YamlScalar.Write(v);
        sb.Append("title: ").Append(Q(rule.Title)).Append('\n');
        sb.Append("id: ").Append(DeterministicId.For("sigma", a.Sample.Sha256, rule.Key)).Append('\n');
        sb.Append("status: experimental\n");
        sb.Append("description: ").Append(Q(rule.Description + $" Draft generated by Blazma Sandbox from one analysis of SHA-256 {a.Sample.Sha256}; observed behavior, not a vetted detection."
            + (a.IsDemo ? " DEMO DATA." : ""))).Append('\n');
        sb.Append("author: ").Append(Q(Author)).Append('\n');
        sb.Append("date: ").Append(InteropData.Day(a.StartedAt)).Append('\n');

        var tags = rule.Techniques.SelectMany(t => t.Tactics.Select(x => "attack." + x.Replace('-', '_')))
            .Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal)
            .Concat(rule.Techniques.Select(t => "attack." + t.Id.ToLowerInvariant())).ToList();
        if (tags.Count > 0)
        {
            sb.Append("tags:\n");
            foreach (var t in tags) sb.Append("    - ").Append(Q(t)).Append('\n');
        }

        sb.Append("logsource:\n    category: ").Append(rule.Category).Append("\n    product: windows\n");
        sb.Append("detection:\n    selection:\n");
        foreach (var (field, values) in rule.Selection)
        {
            sb.Append("        ").Append(field).Append(':');
            if (values.Count == 1)
            {
                sb.Append(' ').Append(Q(EscapeValue(values[0]))).Append('\n');
                continue;
            }
            sb.Append('\n');
            foreach (var v in values) sb.Append("            - ").Append(Q(EscapeValue(v))).Append('\n');
        }
        sb.Append("    condition: selection\n");
        sb.Append("falsepositives:\n    - ").Append(Q(rule.FalsePositive)).Append('\n');
        sb.Append("level: ").Append(rule.Level).Append('\n');
    }

    [GeneratedRegex(@"""[^""]*""|\S+", RegexOptions.CultureInvariant)]
    private static partial Regex ArgumentRegex();

    [GeneratedRegex(@"(?<name>[^\\/:""*?<>|\s]+\.(exe|dll|scr|bat|cmd|ps1|vbs|js|com|pif|msi))", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ProgramRegex();

    [GeneratedRegex(@"^[A-Za-z]:\\Users\\[^\\]+\\(?<rest>.+)$", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex UserProfileRegex();

    [GeneratedRegex(@"^[A-Za-z]:(?<rest>\\.+)$", RegexOptions.CultureInvariant)]
    private static partial Regex DriveRegex();
}
