using System.Globalization;
using System.Text;
using Blazma.Core.Abstractions;
using Blazma.Core.Analysis;
using Blazma.Core.Samples;

namespace Blazma.Reporting.Interop;

/// <summary>
/// A draft YARA rule built from the strings static analysis found in the sample (URLs,
/// commands, registry paths, configuration-like values). It is a starting point for a
/// signature, not a signature: it says so in its metadata, needs no modules, and requires
/// only part of the strings so a rebuilt variant can still match.
/// </summary>
public sealed class YaraRuleGenerator
{
    public const string Author = "Blazma Sandbox (generated)";
    public const int MaxStrings = 12;
    private const int MinLength = 6;
    private const int MaxLength = 200;

    /// <summary>Hosts and paths found in countless legitimate binaries (signing, XML schemas); useless for telling samples apart.</summary>
    private static readonly string[] Common =
    [
        "schemas.microsoft.com", "www.w3.org", "digicert.com", "verisign.com", "symantec.com", "sectigo.com", "globalsign.com",
        "usertrust.com", "comodoca.com", "microsoft.com/pki", "crl.microsoft.com", "ocsp.", "xmlsoap.org", "go.microsoft.com",
    ];

    private readonly Func<bool, Redactor>? _redactorFactory;

    public YaraRuleGenerator(Func<bool, Redactor>? redactorFactory = null) => _redactorFactory = redactorFactory;

    /// <summary>The rule for an analysis' sample, dated with the analysis start. Null when there is no static report or no usable string.</summary>
    public string? Generate(AnalysisResult result, ExportOptions options) =>
        result.Static is null ? null : Generate(result.Static, DateOnly.FromDateTime(result.StartedAt.UtcDateTime), options.Redact);

    /// <summary>The rule text, or null when the report has no distinctive string to build on.</summary>
    public string? Generate(StaticReport report, DateOnly date, bool redact)
    {
        var r = InteropData.Redactor(_redactorFactory, redact);
        var strings = SelectStrings(report, r);
        if (strings.Count == 0) return null;

        var sample = report.Sample;
        var sb = new StringBuilder();
        sb.Append("// Draft YARA rule generated by Blazma Sandbox from static strings. Review and test before use.\n");
        sb.Append("rule ").Append(RuleName(r.Apply(sample.FileName) ?? "", sample.Sha256)).Append("\n{\n");
        sb.Append("    meta:\n");
        Meta(sb, "description", $"Draft rule from static strings of {r.Apply(sample.FileName)}; not a vetted signature. Review before use.");
        Meta(sb, "author", Author);
        Meta(sb, "date", date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture));
        if (InteropData.IsHex(sample.Sha256, 64)) Meta(sb, "sha256", sample.Sha256.ToLowerInvariant());
        if (InteropData.IsHex(report.ImpHash, 32)) Meta(sb, "imphash", report.ImpHash!.ToLowerInvariant());

        sb.Append("    strings:\n");
        for (var i = 0; i < strings.Count; i++)
            sb.Append(CultureInfo.InvariantCulture, $"        $s{i + 1} = \"{Escape(strings[i])}\" ascii wide\n");

        // About half the strings, so small changes between builds still match.
        var needed = strings.Count <= 2 ? strings.Count : Math.Max(2, (strings.Count + 1) / 2);
        var condition = new List<string>();
        if (report.Pe is not null) condition.Add("uint16(0) == 0x5A4D");
        if (FileSizeLimitKb(sample.Size) is { } kb) condition.Add($"filesize < {kb.ToString(CultureInfo.InvariantCulture)}KB");
        condition.Add($"{needed.ToString(CultureInfo.InvariantCulture)} of them");
        sb.Append("    condition:\n        ").Append(string.Join(" and ", condition)).Append("\n}\n");
        return sb.ToString();
    }

    /// <summary>Twice the sample size, rounded up to a round number of KB, so the rule tolerates padding but not unrelated huge files.</summary>
    public static long? FileSizeLimitKb(long size)
    {
        if (size <= 0) return null;
        var kb = (size + 1023) / 1024 * 2;
        var step = kb < 100 ? 10 : kb < 1000 ? 100 : kb < 10_000 ? 1000 : 10_000;
        return (kb + step - 1) / step * step;
    }

    /// <summary>A valid, readable YARA identifier: <c>Blazma_Draft_&lt;name&gt;_&lt;first 8 of SHA-256&gt;</c>.</summary>
    public static string RuleName(string fileName, string sha256)
    {
        var stem = Path.GetFileNameWithoutExtension(fileName);
        var sb = new StringBuilder();
        foreach (var c in stem)
        {
            var ok = char.IsAsciiLetterOrDigit(c);
            if (ok) sb.Append(c);
            else if (sb.Length > 0 && sb[^1] != '_') sb.Append('_');
            if (sb.Length >= 48) break;
        }
        var name = sb.ToString().Trim('_');
        var hash = InteropData.IsHex(sha256, 64) ? sha256[..8].ToLowerInvariant() : null;
        return string.Join('_', new[] { "Blazma_Draft", name, hash }.Where(p => !string.IsNullOrEmpty(p)));
    }

    /// <summary>
    /// YARA text-string escaping: <c>\"</c>, <c>\\</c>, <c>\t</c>, <c>\n</c>, <c>\r</c> and
    /// <c>\xHH</c> for every other control or non-ASCII byte (UTF-8), so the rule file is plain ASCII.
    /// </summary>
    public static string Escape(string value)
    {
        var sb = new StringBuilder(value.Length + 8);
        foreach (var b in Encoding.UTF8.GetBytes(value))
        {
            switch (b)
            {
                case (byte)'"': sb.Append("\\\""); break;
                case (byte)'\\': sb.Append("\\\\"); break;
                case (byte)'\t': sb.Append("\\t"); break;
                case (byte)'\n': sb.Append("\\n"); break;
                case (byte)'\r': sb.Append("\\r"); break;
                default:
                    if (b is < 0x20 or >= 0x7F) sb.Append(CultureInfo.InvariantCulture, $"\\x{b:x2}");
                    else sb.Append((char)b);
                    break;
            }
        }
        return sb.ToString();
    }

    private static void Meta(StringBuilder sb, string key, string value) =>
        sb.Append("        ").Append(key).Append(" = \"").Append(Escape(value)).Append("\"\n");

    /// <summary>
    /// The most distinctive strings: by kind (URLs and commands first), then longest. A string
    /// already contained in a chosen one adds nothing and is skipped. Under redaction a string
    /// that mentions the analyst's user or machine is dropped: redacted, it would not match.
    /// </summary>
    private static List<string> SelectStrings(StaticReport report, Redactor r)
    {
        var candidates = report.Strings.Select(s => (Rank: Rank(s.Kind), s.Value))
            .Concat(report.Artifacts.Select(x => (Rank: Rank(x.Kind), x.Value)))
            .Where(c => c.Rank < int.MaxValue && Usable(c.Value) && r.Apply(c.Value) == c.Value)
            .OrderBy(c => c.Rank).ThenByDescending(c => c.Value.Length).ThenBy(c => c.Value, StringComparer.Ordinal);

        var chosen = new List<string>();
        foreach (var (_, value) in candidates)
        {
            if (chosen.Any(x => x.Contains(value, StringComparison.OrdinalIgnoreCase) || value.Contains(x, StringComparison.OrdinalIgnoreCase))) continue;
            chosen.Add(value);
            if (chosen.Count == MaxStrings) break;
        }
        return chosen;
    }

    private static bool Usable(string value) =>
        value.Length is >= MinLength and <= MaxLength
        && value.All(c => c is >= ' ' and < '\u007f' or '\t')
        && value.Distinct().Count() >= 4
        && !Common.Any(x => value.Contains(x, StringComparison.OrdinalIgnoreCase));

    private static int Rank(InterestingStringKind kind) => kind switch
    {
        InterestingStringKind.Url => 0,
        InterestingStringKind.Command => 1,
        InterestingStringKind.RegistryPath => 2,
        InterestingStringKind.FilePath => 4,
        InterestingStringKind.IpAddress => 5,
        InterestingStringKind.Domain => 6,
        _ => int.MaxValue,
    };

    private static int Rank(ArtifactKind kind) => kind switch
    {
        ArtifactKind.Url or ArtifactKind.DiscordWebhook or ArtifactKind.TelegramBotToken or ArtifactKind.PastebinLink => 0,
        ArtifactKind.MutexName or ArtifactKind.UserAgent or ArtifactKind.OnionAddress or ArtifactKind.Email => 3,
        ArtifactKind.BitcoinAddress or ArtifactKind.EthereumAddress or ArtifactKind.MoneroAddress => 3,
        ArtifactKind.IpAddress => 5,
        ArtifactKind.Domain => 6,
        ArtifactKind.Base64Blob => 7,
        _ => int.MaxValue,
    };
}
